"""Independent versions for semantic validation, decoding, and SAG projection."""

VALIDATOR_VERSION = "sag_semantic_validator_v1"
PROJECTION_VERSION = "sag_semantic_projection_v1"
ISSUE_OUTPUT_SCHEMA_VERSION = "sag_semantic_issue_output_v1"
ISSUE_VALIDATOR_VERSION = "sag_semantic_issue_validator_v1"
ISSUE_VALIDATOR_VERSION_V2 = "sag_semantic_issue_validator_v2"
ISSUE_PROJECTION_VERSION = "sag_semantic_issue_projection_v1"
DECODER_CONTRACT_VERSION = "unconstrained_json_v1"
CANDIDATE_LEDGER_VERSION = "sag_semantic_candidate_ledger_v1"
DECISION_LEDGER_VERSION = "sag_semantic_decision_ledger_v1"
LEDGER_GOLD_AUDIT_VERSION = "sag_semantic_ledger_gold_audit_v1"
MULTIVIEW_INPUT_VERSION = "sag_multiview_input_v2"
PII_REDACTION_VERSION = "sag_pii_redaction_v2"
INFERENCE_PACKET_VERSION = "sag_semantic_inference_packet_v1"
INPUT_PROFILE_VERSION = "sag_semantic_input_profile_v2"
EVAL_MANIFEST_VERSION = "sag_semantic_eval_manifest_v2"
GOLD_SCHEMA_VERSION = "sag_issue_gold_v2"
GOLD_VALIDATION_VERSION = "sag_issue_gold_validation_v1"
ANNOTATION_AGREEMENT_VERSION = "sag_issue_annotation_agreement_v1"
ANNOTATION_ROUND_VERSION = "sag_issue_annotation_round_v1"
ADJUDICATION_MERGE_VERSION = "sag_issue_adjudication_merge_v1"
ORACLE_PROJECTION_VERSION = "sag_oracle_projection_v1"
ORACLE_QUERY_SCHEMA_VERSION = "sag_oracle_query_relevance_v1"
ORACLE_EVALUATION_VERSION = "sag_oracle_retrieval_evaluation_v1"
EVALUATION_VERSION = "sag_semantic_evaluation_v1"
VALIDATOR_REPLAY_VERSION = "sag_semantic_validator_replay_v1"
